// Code generated by goyacc -o y.go bql.y. DO NOT EDIT.

//line bql.y:2
package main

import __yyfmt__ "fmt"

//line bql.y:2

//line bql.y:6
type yySymType struct {
	yys         int
	str         string
	expr        Expression
	exprs       []Expression
	orderBy     OrderBy
	orderBys    []OrderBy
	query       *Query
	whereClause struct {
		field string
		expr  Expression
	}
}

const SELECT = 57346
const FROM = 57347
const WHERE = 57348
const GROUP = 57349
const ORDER = 57350
const BY = 57351
const ASC = 57352
const DESC = 57353
const IDENT = 57354
const STRING = 57355
const EQ = 57356

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SELECT",
	"FROM",
	"WHERE",
	"GROUP",
	"ORDER",
	"BY",
	"ASC",
	"DESC",
	"IDENT",
	"STRING",
	"EQ",
	"','",
	"'('",
	"')'",
	"'*'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line bql.y:133

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 40

var yyAct = [...]int8{
	4, 30, 21, 3, 5, 7, 8, 20, 12, 9,
	15, 32, 7, 14, 25, 28, 7, 13, 5, 34,
	35, 26, 19, 24, 23, 17, 11, 31, 27, 2,
	18, 33, 29, 31, 36, 22, 16, 10, 6, 1,
}

var yyPact = [...]int16{
	25, -1000, 6, 1, -1000, -7, 20, 6, 4, -8,
	18, 10, -1000, -1000, -10, -15, 16, 14, -1000, 0,
	-1000, -1000, -1000, 12, 6, 2, 6, -3, -1000, -4,
	-1000, 9, 6, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 39, 3, 0, 38, 37, 36, 35, 32, 1,
	31, 30,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 3, 4, 4, 5,
	5, 11, 6, 6, 7, 7, 8, 8, 9, 10,
	10, 10,
}

var yyR2 = [...]int8{
	0, 6, 1, 3, 1, 4, 4, 0, 2, 0,
	2, 3, 0, 3, 0, 3, 1, 3, 2, 0,
	1, 1,
}

var yyChk = [...]int16{
	-1000, -1, 4, -2, -3, 12, -4, 15, 5, 16,
	-5, 6, -3, 13, -2, 18, -6, 7, -11, 12,
	17, 17, -7, 8, 9, 14, 9, -2, 13, -8,
	-9, -3, 15, -10, 10, 11, -9,
}

var yyDef = [...]int8{
	0, -2, 0, 7, 2, 4, 9, 0, 0, 0,
	12, 0, 3, 8, 0, 0, 14, 0, 10, 0,
	5, 6, 1, 0, 0, 0, 0, 13, 11, 15,
	16, 19, 0, 18, 20, 21, 17,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	16, 17, 18, 3, 15,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-6 : yypt+1]
//line bql.y:41
		{
			yyVAL.query = &Query{
				Select:     yyDollar[2].exprs,
				From:       yyDollar[3].str,
				Where:      yyDollar[4].whereClause.expr,
				WhereField: yyDollar[4].whereClause.field,
				GroupBy:    yyDollar[5].exprs,
				OrderBy:    yyDollar[6].orderBys,
			}
			yylex.(*BQLLexer).result = yyVAL.query
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line bql.y:56
		{
			yyVAL.exprs = []Expression{yyDollar[1].expr}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line bql.y:60
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line bql.y:67
		{
			yyVAL.expr = Expression{Literal: yyDollar[1].str}
		}
	case 5:
		yyDollar = yyS[yypt-4 : yypt+1]
//line bql.y:71
		{
			yyVAL.expr = Expression{FuncName: yyDollar[1].str, FuncArgs: yyDollar[3].exprs}
		}
	case 6:
		yyDollar = yyS[yypt-4 : yypt+1]
//line bql.y:75
		{
			yyVAL.expr = Expression{FuncName: yyDollar[1].str, FuncArgs: []Expression{{Literal: "*"}}}
		}
	case 7:
		yyDollar = yyS[yypt-0 : yypt+1]
//line bql.y:81
		{
			yyVAL.str = ""
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line bql.y:82
		{
			yyVAL.str = yyDollar[2].str
		}
	case 9:
		yyDollar = yyS[yypt-0 : yypt+1]
//line bql.y:86
		{
			yyVAL.whereClause.field = ""
			yyVAL.whereClause.expr = Expression{}
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line bql.y:87
		{
			yyVAL.whereClause = yyDollar[2].whereClause
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line bql.y:92
		{
			yyVAL.whereClause.field = yyDollar[1].str
			yyVAL.whereClause.expr = Expression{Literal: yyDollar[3].str}
		}
	case 12:
		yyDollar = yyS[yypt-0 : yypt+1]
//line bql.y:100
		{
			yyVAL.exprs = nil
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line bql.y:101
		{
			yyVAL.exprs = yyDollar[3].exprs
		}
	case 14:
		yyDollar = yyS[yypt-0 : yypt+1]
//line bql.y:105
		{
			yyVAL.orderBys = nil
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line bql.y:106
		{
			yyVAL.orderBys = yyDollar[3].orderBys
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line bql.y:111
		{
			yyVAL.orderBys = []OrderBy{yyDollar[1].orderBy}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line bql.y:115
		{
			yyVAL.orderBys = append(yyDollar[1].orderBys, yyDollar[3].orderBy)
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line bql.y:122
		{
			yyVAL.orderBy = OrderBy{Expression: yyDollar[1].expr, Ascending: (yyDollar[2].str != "DESC")}
		}
	case 19:
		yyDollar = yyS[yypt-0 : yypt+1]
//line bql.y:128
		{
			yyVAL.str = "ASC"
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line bql.y:129
		{
			yyVAL.str = "ASC"
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line bql.y:130
		{
			yyVAL.str = "DESC"
		}
	}
	goto yystack /* stack new state and value */
}
